CREATE TABLE `page1` (
  `id` bigint(15) NOT NULL AUTO_INCREMENT,
  `date` date default NULL,
  `group_id` tinyint(1) NOT NULL default '0',
  `ip` varchar(45) NOT NULL default '',
  `mac` varchar(45) NOT NULL default '',
  `sent_bytes` int(11) unsigned NOT NULL default '0',
  `recv_bytes` int(11) unsigned NOT NULL default '0',
  `sent_pkts` int(11) unsigned NOT NULL default '0',
  `recv_pkts` int(11) unsigned NOT NULL default '0',
  `intf` varchar(16) NOT NULL default '',
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `group_id` (`group_id`),
  KEY `ip` (`ip`),
  KEY `mac` (`mac`),
  KEY `sent_bytes` (`sent_bytes`),
  KEY `recv_bytes` (`recv_bytes`),
  KEY `sent_pkts` (`sent_pkts`),
  KEY `recv_pkts` (`recv_pkts`),
  KEY `intf` (`intf`)
);

CREATE TABLE `page2` (
  `id` bigint(15) NOT NULL AUTO_INCREMENT,
  `date` date default NULL,
  `ip` varchar(45) NOT NULL default '',
  `mac` varchar(45) NOT NULL default '',
  `remote_ip` varchar(45) NOT NULL default '',
  `sent_bytes` int(11) unsigned NOT NULL default '0',
  `recv_bytes` int(11) unsigned NOT NULL default '0',
  `sent_pkts` int(11) unsigned NOT NULL default '0',
  `recv_pkts` int(11) unsigned NOT NULL default '0',
  `port` smallint(5) unsigned NOT NULL default '0',
  `prot` tinyint(3) unsigned NOT NULL default '0',
  `intf` varchar(16) NOT NULL default '',
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `ip` (`ip`),
  KEY `mac` (`mac`),
  KEY `remote_ip` (`remote_ip`),
  KEY `sent_bytes` (`sent_bytes`),
  KEY `recv_bytes` (`recv_bytes`),
  KEY `sent_pkts` (`sent_pkts`),
  KEY `recv_pkts` (`recv_pkts`),
  KEY `port` (`port`),
  KEY `prot` (`prot`),
  KEY `intf` (`intf`)
);
